CREATE OR REPLACE PACKAGE PESQUISA IS

    PROCEDURE MAIN (PRM_USUARIO     VARCHAR2 DEFAULT NULL,
                    PRM_CLIENTE     VARCHAR2 DEFAULT NULL,
                    PRM_ID_PESQUISA VARCHAR2 DEFAULT NULL);
            
    PROCEDURE MONTA_PERGUNTA (PRM_ID_PESQUISA VARCHAR2);

    PROCEDURE GRAVA_RESPOSTA (PRM_ID_PESQUISA VARCHAR2 DEFAULT NULL,
                              PRM_CLIENTE VARCHAR2 DEFAULT NULL,
                              PRM_USUARIO VARCHAR2 DEFAULT NULL,
                              PRM_RESPOSTAS VARCHAR2 DEFAULT NULL,
                              PRM_CD_PERGUNTA VARCHAR2 DEFAULT NULL,
                              PRM_CD_OPCAO     VARCHAR2 DEFAULT NULL,
                              PRM_JUSTIFICATIVA VARCHAR2 DEFAULT NULL);

    PROCEDURE TELA_AVISO  (PRM_ID_PESQUISA Varchar2 Default Null,
                           PRM_ID_USUARIO VARCHAR2 DEFAULT NULL,
                           PRM_CLIENTE VARCHAR2 DEFAULT NULL);

    FUNCTION TRADUZIR (PRM_TEXTO VARCHAR2) RETURN VARCHAR2;
	
    FUNCTION GET_TRANSLATOR ( PRM_TEXTO         VARCHAR2,
                              PRM_ORIGEM_LANG   VARCHAR2,
                              PRM_DESTINO_LANG  VARCHAR2 ) RETURN VARCHAR2;
	
END PESQUISA;
/
